FROM node:18-alpine as builder

WORKDIR /frontendcode

COPY package*.json ./

RUN npm install 

COPY . .

RUN npm run build

RUN ls -la ./.next

FROM node:22-alpine

WORKDIR /frontend

COPY --from=builder /frontendcode/.next ./.next

RUN npm install

EXPOSE 3000

CMD ["npm","run", "dev"]