
services:
  db:
    image: mysql:latest  # Uses official MySQL image
    container_name: panployer-mysql
    platform: linux/amd64
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
  api:
    platform: linux/amd64
    build: ./api
    container_name: api_container
    restart: on-failure:5
    # volumes: Don't need to use during Production build 
    # - './api:/apicode'
    # - '/apicode/node_modules'
    ports:
      - "5001:5001"
    depends_on:
      db: 
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  frontend:
    platform: linux/amd64
    build: ./frontend  # Uses frontend/Dockerfile
    container_name: frontend_container
    # volumes: Don't use this during proudction build.
    #   - './frontend:/app'
    #   - '/app/node_modules'
    ports:
      - "3000:3000"
    depends_on:
      - api

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    entrypoint: /bin/bash
    command: >
      -c "/opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start --optimized --hostname=localhost --https-certificate-file=/etc/x509/https/tls.crt --https-certificate-key-file=/etc/x509/https/tls.key"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./certs:/etc/x509/https
    ports:
      - "8443:8443"
    depends_on:
      db:
        condition: service_healthy


  
volumes:
  db_data:
  apicode:
  frontendcode: 
  keycloak_data: