version: "3.8"

services:
  backend:
    build: ./backend  # Uses backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydatabase

  frontend:
    build: .  # Uses frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: mysql:latest  # Uses official MySQL image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"