version: "3.8"

services:
  db:
    image: mysql:latest  # Uses official MySQL image
    container_name: panployer-mysql
    restart: always
    environment: 
      - .env
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pexample"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
  api:
    build: ./api # Uses api/Dockerfile
    container_name: api_container
    volumes: ['./api:/apicode']
    ports:
      - "5001:5001"
    depends_on:
      db: 
        condition: service_healthy
    environment:
      - .env

  frontend:
    build: ./frontend  # Uses frontend/Dockerfile
    container_name: frontend_container
    volumes: ['./frontend:/app']
    ports:
      - "3000:3000"
    depends_on:
      - api
  
volumes:
  db_data:
  apicode:
  frontendcode: