version: "3.8"

services:
  backend:
    build: backend/. # Uses backend/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DB_HOST=panployer-mysql
      - DB_USER=root
      - DB_PASSWORD=PanPloyer@1234
      - DB_NAME=Signup_schema

  frontend:
    build: .  # Uses frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:latest  # Uses official MySQL image
    container_name: panployer-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PanPloyer@1234
      MYSQL_DATABASE: Signup_schema
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
volumes:
  db_data: