version: "3.8"

services:
  api:
    build: ./api # Uses api/Dockerfile
    container_name: api_container
    volumes: ['./api:/apicode']
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DB_HOST=panployer-mysql
      - DB_USER=root
      - DB_PASSWORD=PanPloyer@1234
      - DB_NAME=Signup_schema

  frontend:
    build: ./frontend/src  # Uses frontend/Dockerfile
    container_name: frontend_container
    volumes: ['./frontend/src:/frontendcode']
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: mysql:latest  # Uses official MySQL image
    container_name: panployer-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PanPloyer@1234
      MYSQL_DATABASE: Signup_schema
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
volumes:
  db_data:
  apicode:
  frontendcode: